export const metadata = { title: 'Privacy Policy' };
export default function Privacy() {
  return <main className="document-page"><h1>Luma Privacy Policy.</h1><article className="document">
    <p>Updated September 16, 2026. This policy describes the data used by Luma’s USDC-on-Arc link service. Luma is independent of Arc and Circle.</p>
    <h2>Wallets and sign-in</h2><p>Luma uses wallet addresses to display deposits, verify recovery requests, and send transactions. Privy provides sign-in and embedded wallets. Depending on your sign-in method, Privy and your chosen login provider may process account identifiers, linked wallet addresses, profile information, and device or connection data. Luma’s claim service verifies your Privy session and receiving wallet to authorize sponsored claims.</p>
    <h2>Claim links and encrypted backups</h2><p>A complete claim link contains a secret that can redeem the deposit. After a deposit confirms, Luma attempts to send the link’s secret fragment and sending wallet address to its own backup service. That service validates the deposit and encrypts the backup before storing it in Supabase. It also stores the sending wallet, deposit ID, network, escrow, and creation time to locate backups.</p><p>This is server-managed encryption, not end-to-end encryption: Luma’s backend processes the secret and can decrypt a backup using its server-held key. Recovery through the app requires a signature from the original sending wallet. Public history responses exclude the secret. Keep your own copy if a backup fails.</p>
    <h2>Data in your browser</h2><p>The app stores local deposit history and pending-send information. Pending-send and opened-claim secrets may be held in tab session storage to survive a refresh. On the claim page, Luma removes the secret fragment from the address bar before loading Privy. Fragments are not included in the initial page request; the backup request described above deliberately transmits them separately.</p><p>Wallet and sign-in providers may use cookies or browser storage for sessions and security. Browser extensions, clipboard tools, and anyone who receives your full link may be able to read it. Do not send claim links in support messages.</p>
    <h2>Sponsored claims</h2><p>The relay receives your authentication token, receiving address, deposit details, and a recipient-bound claim signature. It does not receive the claim private key. Supabase stores relay transaction records, account identifiers, timestamps, and usage limits so claims can be retried safely and sponsorship abuse can be limited.</p>
    <h2>Public blockchain records</h2><p>Wallet and signer addresses, amounts, transaction data, and claim or cancellation events are public on Arc. These records may be linked to your identity through your account or other activity. Luma cannot erase blockchain records or make transfers confidential.</p>
    <h2>Service providers</h2><p>Privy supports authentication and wallets; Supabase hosts backup and relay data. Hosting, RPC, wallet, and login providers may process IP addresses, browser details, and request metadata while delivering their services. See <a href="https://www.privy.io/privacy-policy" target="_blank" rel="noreferrer">Privy’s privacy policy</a> and <a href="https://supabase.com/privacy" target="_blank" rel="noreferrer">Supabase’s privacy policy</a>, as well as your wallet and login provider’s policies.</p><p>The Luma application code does not add advertising trackers or a separate analytics service. This does not mean its infrastructure and authentication providers collect no operational or usage data.</p>
    <h2>Storage and your controls</h2><p>You can disconnect your wallet, sign out, and clear browser site data. Save needed links first. These actions do not delete server backups, relay records, provider account data, or blockchain records, and do not cancel deposits.</p><p>The current version has no automatic deletion schedule or self-service server-data deletion feature. Backups and relay records may remain after a link is claimed or cancelled. Provider retention is governed separately by their policies. Only an onchain cancellation by the sending wallet can recover an unclaimed deposit; deleting a saved link does not move the funds.</p>
  </article></main>;
}
