import { createPublicClient, createWalletClient, defineChain, http } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import fs from 'node:fs';
import { compile } from './compile-contracts.mjs';
if (fs.existsSync('.env.local')) process.loadEnvFile('.env.local');
const testnet = process.env.NEXT_PUBLIC_ARC_NETWORK === 'testnet';
const id = testnet ? 5042002 : 5042;
if (process.env.CONFIRM_DEPLOY_CHAIN_ID !== String(id)) throw new Error(`Set CONFIRM_DEPLOY_CHAIN_ID=${id} to explicitly authorize a deployment on this chain.`);
if (!process.env.DEPLOYER_PRIVATE_KEY) throw new Error('Provide DEPLOYER_PRIVATE_KEY in the process environment. Never use a NEXT_PUBLIC variable.');
const url = process.env.NEXT_PUBLIC_ARC_RPC_URL || (testnet ? 'https://rpc.testnet.arc.io' : 'https://rpc.mainnet.arc.io');
const chain = defineChain({ id, name: testnet ? 'Arc Testnet' : 'Arc', nativeCurrency: { name: 'USDC', symbol: 'USDC', decimals: 18 }, rpcUrls: { default: { http: [url] } } });
const publicClient = createPublicClient({ chain, transport: http(url) });
if (await publicClient.getChainId() !== id) throw new Error('RPC chain ID mismatch.');
const wallet = createWalletClient({ account: privateKeyToAccount(process.env.DEPLOYER_PRIVATE_KEY), chain, transport: http(url) });
const contract = compile()['ArcEscrow.sol'].ArcEscrow;
const fees = await publicClient.estimateFeesPerGas();
const maxFeePerGas = fees.maxFeePerGas < 20_000_000_000n ? 20_000_000_000n : fees.maxFeePerGas;
const hash = await wallet.deployContract({ abi: contract.abi, bytecode: `0x${contract.evm.bytecode.object}`, maxFeePerGas, maxPriorityFeePerGas: fees.maxPriorityFeePerGas });
console.log(`Deployment submitted: ${hash}`);
const receipt = await publicClient.waitForTransactionReceipt({ hash });
if (receipt.status !== 'success' || !receipt.contractAddress) throw new Error('Deployment failed.');
console.log(`NEXT_PUBLIC_ARC_ESCROW_ADDRESS=${receipt.contractAddress}`);
